# SPDX-License-Identifier: Apache-2.0
"""
Tests for MLXLanguageModel prompt cache and stream generation finish logic.

Generated by MiniMax-M2.5 via openclaw simulation, reviewed and fixed by Claude.
"""

from unittest.mock import patch

import pytest

from vllm_mlx.models.llm import GenerationOutput, MLXLanguageModel, StreamingOutput


class MockCacheEntry:
    """Mock cache entry that mimics mlx_lm.models.cache.Cache."""

    def __init__(self, offset: int = 0):
        self._offset = offset

    @property
    def offset(self) -> int:
        return self._offset

    def trim(self, amount: int) -> None:
        self._offset = max(0, self._offset - amount)

    def is_trimmable(self) -> bool:
        return True


# ---------------------------------------------------------------------------
# _find_common_prefix_len
# ---------------------------------------------------------------------------


class TestFindCommonPrefixLen:
    """Tests for _find_common_prefix_len method."""

    @pytest.fixture
    def model(self):
        model = MLXLanguageModel("test-model")
        model._loaded = True
        return model

    def test_empty_cached(self, model):
        model._cached_token_ids = []
        assert model._find_common_prefix_len([1, 2, 3]) == 0

    def test_empty_new(self, model):
        model._cached_token_ids = [1, 2, 3]
        assert model._find_common_prefix_len([]) == 0

    def test_both_empty(self, model):
        model._cached_token_ids = []
        assert model._find_common_prefix_len([]) == 0

    def test_no_common_prefix(self, model):
        model._cached_token_ids = [1, 2, 3]
        assert model._find_common_prefix_len([4, 5, 6]) == 0

    def test_full_common_prefix(self, model):
        model._cached_token_ids = [1, 2, 3, 4, 5]
        assert model._find_common_prefix_len([1, 2, 3]) == 3

    def test_partial_common_prefix(self, model):
        model._cached_token_ids = [1, 2, 3, 4, 5]
        assert model._find_common_prefix_len([1, 2, 6, 7]) == 2

    def test_cached_longer_than_new(self, model):
        model._cached_token_ids = [1, 2, 3, 4, 5, 6, 7]
        assert model._find_common_prefix_len([1, 2, 3]) == 3

    def test_new_longer_than_cached(self, model):
        model._cached_token_ids = [1, 2]
        assert model._find_common_prefix_len([1, 2, 3, 4, 5]) == 2

    def test_identical_tokens(self, model):
        model._cached_token_ids = [1, 2, 3, 4, 5]
        assert model._find_common_prefix_len([1, 2, 3, 4, 5]) == 5

    def test_single_token_match(self, model):
        model._cached_token_ids = [1]
        assert model._find_common_prefix_len([1, 2, 3]) == 1

    def test_single_token_no_match(self, model):
        model._cached_token_ids = [1]
        assert model._find_common_prefix_len([2, 3]) == 0


# ---------------------------------------------------------------------------
# _prepare_cache_for_prompt
# ---------------------------------------------------------------------------


class TestPrepareCacheForPrompt:
    """Tests for _prepare_cache_for_prompt method."""

    @pytest.fixture
    def model(self):
        model = MLXLanguageModel("test-model")
        model._loaded = True
        return model

    def test_first_call_no_cache(self, model):
        """First call creates new cache and returns all tokens."""
        with patch("mlx_lm.models.cache.make_prompt_cache") as mock_make_cache:
            mock_make_cache.return_value = [MockCacheEntry(0)]
            result = model._prepare_cache_for_prompt([1, 2, 3, 4, 5])

            assert result == [1, 2, 3, 4, 5]
            assert model._prompt_cache is not None
            assert model._cached_token_ids == []

    def test_full_cache_hit(self, model):
        """Exact same prompt — returns empty suffix."""
        model._prompt_cache = [MockCacheEntry(5)]
        model._cached_token_ids = [1, 2, 3, 4, 5]

        result = model._prepare_cache_for_prompt([1, 2, 3, 4, 5])

        assert result == []
        assert model._cached_token_ids == [1, 2, 3, 4, 5]

    def test_partial_cache_hit(self, model):
        """New prompt shares partial prefix with cached tokens."""
        model._prompt_cache = [MockCacheEntry(10)]
        model._cached_token_ids = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

        result = model._prepare_cache_for_prompt([1, 2, 3, 8, 9])

        # common_len=3, suffix=[8,9], cache trimmed by (10-3)=7
        assert result == [8, 9]
        assert model._cached_token_ids == [1, 2, 3]

    def test_no_cache_hit_resets_cache(self, model):
        """No prefix match resets cache entirely."""
        model._prompt_cache = [MockCacheEntry(10)]
        model._cached_token_ids = [1, 2, 3, 4, 5]

        result = model._prepare_cache_for_prompt([6, 7, 8])

        assert result == [6, 7, 8]
        assert model._cached_token_ids == []

    def test_empty_prompt(self, model):
        """Empty prompt with existing cache."""
        model._prompt_cache = [MockCacheEntry(5)]
        model._cached_token_ids = [1, 2, 3, 4, 5]

        result = model._prepare_cache_for_prompt([])

        assert result == []

    def test_cache_with_generated_tokens(self, model):
        """Cache offset includes generated tokens from previous call."""
        # Cache has prompt(5) + generated(5) = offset 10
        model._prompt_cache = [MockCacheEntry(10)]
        model._cached_token_ids = [1, 2, 3, 4, 5]

        # Same prompt — full hit, trim generated tokens
        result = model._prepare_cache_for_prompt([1, 2, 3, 4, 5])

        # Should trim 10-5=5 generated tokens
        assert result == []
        assert model._cached_token_ids == [1, 2, 3, 4, 5]
        # Cache offset should now be 5 (trimmed 5)
        assert model._prompt_cache[0].offset == 5

    def test_new_prompt_longer_than_cache(self, model):
        """New prompt extends beyond cached tokens."""
        model._prompt_cache = [MockCacheEntry(3)]
        model._cached_token_ids = [1, 2, 3]

        result = model._prepare_cache_for_prompt([1, 2, 3, 4, 5, 6, 7])

        assert result == [4, 5, 6, 7]
        assert model._cached_token_ids == [1, 2, 3]


# ---------------------------------------------------------------------------
# _save_cache_snapshot
# ---------------------------------------------------------------------------


class TestSaveCacheSnapshot:
    """Tests for _save_cache_snapshot method."""

    @pytest.fixture
    def model(self):
        model = MLXLanguageModel("test-model")
        model._loaded = True
        return model

    def test_saves_token_ids(self, model):
        model._prompt_cache = [MockCacheEntry(5)]
        model._save_cache_snapshot([1, 2, 3, 4, 5])
        assert model._cached_token_ids == [1, 2, 3, 4, 5]

    def test_saves_empty_list(self, model):
        model._prompt_cache = [MockCacheEntry(0)]
        model._save_cache_snapshot([])
        assert model._cached_token_ids == []

    def test_no_cache_ignores_call(self, model):
        model._prompt_cache = None
        model._save_cache_snapshot([1, 2, 3])
        assert model._cached_token_ids == []

    def test_creates_copy_not_reference(self, model):
        """Saved list should be a copy, not a reference."""
        token_ids = [1, 2, 3]
        model._prompt_cache = [MockCacheEntry(3)]
        model._save_cache_snapshot(token_ids)

        # Modify original — cached should be unaffected
        token_ids.append(4)
        assert model._cached_token_ids == [1, 2, 3]


# ---------------------------------------------------------------------------
# Cache integration scenarios
# ---------------------------------------------------------------------------


class TestCacheIntegration:
    """Integration tests for multi-turn cache reuse scenarios."""

    @pytest.fixture
    def model(self):
        model = MLXLanguageModel("test-model")
        model._loaded = True
        return model

    def test_multi_turn_growing_prompt(self, model):
        """Simulate multi-turn conversation with growing prompt."""
        # Pre-set cache (simulating first call already happened)
        model._prompt_cache = [MockCacheEntry(15)]  # 5 prompt + 10 generated
        model._cached_token_ids = [1, 2, 3, 4, 5]

        # Turn 2: same prefix + new user message tokens
        result = model._prepare_cache_for_prompt([1, 2, 3, 4, 5, 6, 7, 8])
        assert result == [6, 7, 8]
        assert model._cached_token_ids == [1, 2, 3, 4, 5]

    def test_completely_different_prompt(self, model):
        """Switching to a completely different prompt resets cache."""
        model._prompt_cache = [MockCacheEntry(8)]
        model._cached_token_ids = [1, 2, 3]

        result = model._prepare_cache_for_prompt([10, 20, 30, 40])
        assert result == [10, 20, 30, 40]
        assert model._cached_token_ids == []
        assert model._prompt_cache[0].offset == 0  # fully reset

    def test_exact_repeat_prompt(self, model):
        """Exact same prompt should return empty suffix."""
        model._prompt_cache = [MockCacheEntry(12)]  # 5 prompt + 7 generated
        model._cached_token_ids = [1, 2, 3, 4, 5]

        result = model._prepare_cache_for_prompt([1, 2, 3, 4, 5])
        assert result == []
        # Cache trimmed from 12 to 5
        assert model._prompt_cache[0].offset == 5


# ---------------------------------------------------------------------------
# StreamingOutput and GenerationOutput dataclasses
# ---------------------------------------------------------------------------


class TestDataclasses:
    """Tests for StreamingOutput and GenerationOutput dataclasses."""

    def test_streaming_output_defaults(self):
        out = StreamingOutput(text="hello", token=42)
        assert out.text == "hello"
        assert out.token == 42
        assert out.finished is False
        assert out.finish_reason is None
        assert out.logprobs is None
        assert out.prompt_tokens == 0

    def test_streaming_output_finished(self):
        out = StreamingOutput(
            text=".",
            token=1,
            finished=True,
            finish_reason="stop",
            prompt_tokens=100,
        )
        assert out.finished is True
        assert out.finish_reason == "stop"
        assert out.prompt_tokens == 100

    def test_generation_output_defaults(self):
        out = GenerationOutput(text="hello world", tokens=[1, 2])
        assert out.text == "hello world"
        assert out.tokens == [1, 2]
        assert out.finish_reason is None

    def test_generation_output_with_finish(self):
        out = GenerationOutput(text="done", tokens=[1], finish_reason="length")
        assert out.finish_reason == "length"


# ---------------------------------------------------------------------------
# Real upstream cache types (P1/P2 regression tests)
# ---------------------------------------------------------------------------

mlx_lm_cache = pytest.importorskip("mlx_lm.models.cache", reason="mlx-lm not installed")
ArraysCache = mlx_lm_cache.ArraysCache
CacheList = mlx_lm_cache.CacheList
KVCache = mlx_lm_cache.KVCache


def _make_dirty_arrays_cache(size: int = 4) -> "ArraysCache":
    """Create an ArraysCache with non-None entries (dirty state)."""
    import mlx.core as mx

    cache = ArraysCache(size)
    for i in range(size):
        cache[i] = mx.ones((1, 4))
    return cache


class TestNonTrimmableCacheReset:
    """Tests that non-trimmable caches (ArraysCache, CacheList) are properly
    reset when the prompt changes — regression tests for P1-a and P1-b."""

    @pytest.fixture
    def model(self):
        model = MLXLanguageModel("test-model")
        model._loaded = True
        return model

    def test_pure_arrays_cache_exact_repeat_resets(self, model):
        """P1-a: Pure ArraysCache model — exact repeat must not reuse dirty
        recurrent state."""
        dirty = _make_dirty_arrays_cache()
        model._prompt_cache = [dirty]
        model._cached_token_ids = [1, 2, 3]

        with patch.object(model, "_make_fresh_cache") as mock_fresh:
            fresh = _make_dirty_arrays_cache(4)
            # Make it truly fresh (empty)
            fresh_clean = ArraysCache(4)
            mock_fresh.return_value = [fresh_clean]

            result = model._prepare_cache_for_prompt([1, 2, 3])

        # Non-trimmable → must recreate, returning all tokens for re-prefill
        assert result == [1, 2, 3]
        assert model._cached_token_ids == []

    def test_pure_arrays_cache_growing_prompt_resets(self, model):
        """P1-a: Pure ArraysCache model — growing prompt must return all
        tokens, not just the suffix."""
        dirty = _make_dirty_arrays_cache()
        model._prompt_cache = [dirty]
        model._cached_token_ids = [1, 2, 3]

        with patch.object(model, "_make_fresh_cache") as mock_fresh:
            mock_fresh.return_value = [ArraysCache(4)]
            result = model._prepare_cache_for_prompt([1, 2, 3, 4, 5, 6])

        # Non-trimmable → full re-prefill
        assert result == [1, 2, 3, 4, 5, 6]
        assert model._cached_token_ids == []

    def test_pure_arrays_cache_different_prompt_resets(self, model):
        """P1-a: Pure ArraysCache — different prompt also resets."""
        dirty = _make_dirty_arrays_cache()
        model._prompt_cache = [dirty]
        model._cached_token_ids = [1, 2, 3]

        with patch.object(model, "_make_fresh_cache") as mock_fresh:
            mock_fresh.return_value = [ArraysCache(4)]
            result = model._prepare_cache_for_prompt([7, 8, 9])

        assert result == [7, 8, 9]
        assert model._cached_token_ids == []

    def test_cachelist_mixed_arrays_kv_resets(self, model):
        """P1-b: CacheList(ArraysCache, KVCache) — is_trimmable() returns
        False because ArraysCache is not trimmable. Must recreate."""
        mixed = CacheList(_make_dirty_arrays_cache(), KVCache())
        assert not mixed.is_trimmable()  # Verify precondition

        model._prompt_cache = [mixed]
        model._cached_token_ids = [1, 2, 3]

        with patch.object(model, "_make_fresh_cache") as mock_fresh:
            mock_fresh.return_value = [CacheList(ArraysCache(4), KVCache())]
            result = model._prepare_cache_for_prompt([1, 2, 3])

        assert result == [1, 2, 3]
        assert model._cached_token_ids == []

    def test_cachelist_all_kv_is_trimmable(self, model):
        """CacheList(KVCache, KVCache) IS trimmable — trim works normally."""
        kv1 = KVCache()
        kv1.offset = 5
        kv2 = KVCache()
        kv2.offset = 5
        cl = CacheList(kv1, kv2)
        assert cl.is_trimmable()

        model._prompt_cache = [cl]
        model._cached_token_ids = [1, 2, 3, 4, 5]

        result = model._prepare_cache_for_prompt([1, 2, 3, 6, 7])

        # Trimmable → partial trim works, returns suffix
        assert result == [6, 7]
        assert model._cached_token_ids == [1, 2, 3]
        assert kv1.offset == 3
        assert kv2.offset == 3

    def test_kvcache_full_reset_on_no_overlap(self, model):
        """Real KVCache — no overlap resets offset to 0."""
        kv = KVCache()
        kv.offset = 10
        model._prompt_cache = [kv]
        model._cached_token_ids = [1, 2, 3]

        result = model._prepare_cache_for_prompt([7, 8, 9])

        assert result == [7, 8, 9]
        assert model._cached_token_ids == []
        assert kv.offset == 0

    def test_kvcache_exact_repeat_trims_generated(self, model):
        """Real KVCache — exact repeat trims generated tokens only."""
        kv = KVCache()
        kv.offset = 12  # 5 prompt + 7 generated
        model._prompt_cache = [kv]
        model._cached_token_ids = [1, 2, 3, 4, 5]

        result = model._prepare_cache_for_prompt([1, 2, 3, 4, 5])

        assert result == []
        assert kv.offset == 5
