# SPDX-License-Identifier: Apache-2.0
"""Tests for MiniMaxReasoningParser.

Generated by MiniMax-M2.5 via vllm-mlx, reviewed and fixed by human.
"""

from unittest.mock import MagicMock

import pytest

from vllm_mlx.reasoning.minimax_parser import MiniMaxReasoningParser


class TestMiniMaxReasoningParserInit:
    """Test parser initialization and reset."""

    def test_default_init(self):
        parser = MiniMaxReasoningParser()
        assert parser._buffer == ""
        assert parser._decided is False
        assert parser._is_reasoning is False
        assert parser._transition_pos == 0

    def test_init_with_tokenizer(self):
        mock_tokenizer = MagicMock()
        parser = MiniMaxReasoningParser(tokenizer=mock_tokenizer)
        assert parser._buffer == ""
        assert parser._decided is False

    def test_reset_state(self):
        parser = MiniMaxReasoningParser()
        parser._buffer = "some text"
        parser._decided = True
        parser._is_reasoning = True
        parser._transition_pos = 100
        parser.reset_state()

        assert parser._buffer == ""
        assert parser._decided is False
        assert parser._is_reasoning is False
        assert parser._transition_pos == 0


class TestExtractReasoningExplicitTags:
    """Test explicit <think> tag handling."""

    def test_explicit_standard_tags(self):
        parser = MiniMaxReasoningParser()
        output = "<think>Let me think about this.</think>Here is the answer."

        reasoning, content = parser.extract_reasoning(output)

        assert reasoning == "Let me think about this."
        assert content == "Here is the answer."

    def test_explicit_tag_no_content(self):
        parser = MiniMaxReasoningParser()
        output = "<think>Just thinking here.</think>"

        reasoning, content = parser.extract_reasoning(output)

        assert reasoning == "Just thinking here."
        assert content is None

    def test_explicit_tag_only_content_after(self):
        parser = MiniMaxReasoningParser()
        output = "<think></think>Some content"

        reasoning, content = parser.extract_reasoning(output)

        assert reasoning is None
        assert content == "Some content"

    def test_explicit_tag_with_whitespace(self):
        parser = MiniMaxReasoningParser()
        output = "<think>  Reasoning here.  </think>  Content here.  "

        reasoning, content = parser.extract_reasoning(output)

        assert reasoning == "Reasoning here."
        assert content == "Content here."


class TestDirectContentDetection:
    """Test detection of direct content (no reasoning)."""

    @pytest.mark.parametrize(
        "content",
        [
            "```python\nprint('hello')\n```",
            "<minimax:tool_call>some tool</minimax:tool_call>",
            "<tool_call>call</tool_call>",
            "<invoke name='test'>",
            "# Heading",
            "## Subheading",
            '{"key": "value"}',
            '["item1", "item2"]',
        ],
    )
    def test_direct_content_patterns(self, content):
        parser = MiniMaxReasoningParser()
        reasoning, result_content = parser.extract_reasoning(content)

        assert reasoning is None
        assert result_content == content


class TestReasoningStartPatterns:
    """Test reasoning start pattern detection."""

    @pytest.mark.parametrize(
        "text",
        [
            "The user asks for a poem.",
            "The user wants to know about AI.",
            "The user is asking for help.",
            "The user requests a summary.",
            "I need to analyze this.",
            "I should consider the options.",
            "I will provide the answer.",
            "I can help with that.",
            "I want to explain this.",
            "I have to make a decision.",
            "I must complete this task.",
            "I am going to solve this.",
            "Let me think about this.",
            "Let me check the details.",
            "Let me analyze the problem.",
            "Let me figure this out.",
            "Let me consider the options.",
            "Let me look at the data.",
            "Let me read the input.",
            "Let me review the context.",
            "Let me process this request.",
            "This is a complex question.",
            "This requires careful thought.",
            "This seems like a good approach.",
            "This looks like a request for help.",
            "This appears to be about code.",
            "First, I need to understand.",
            "First, let me explain.",
            "First, we should consider.",
            "So the user wants to know.",
            "Now I need to figure this out.",
            "OK let me think about this.",
            "Okay, I should help with this.",
            "Alright, let me proceed.",
            "Well, I need to think about this.",
            "what's worth storing in memory.",
            "Analyzing the request carefully.",
            "Thinking about the best approach.",
            "Processing the input data.",
            "Considering all options.",
            "Evaluating the requirements.",
            "Extracting the key information.",
            # Chinese reasoning patterns
            "用户想让我写一个测试文件。",
            "用户要知道这个函数的用法。",
            "用户需要帮助修复bug。",
            "用户问如何优化代码。",
            "用户请求一个总结。",
            "用户让我分析代码。",
            "我需要分析这段代码。",
            "我应该先看看文件内容。",
            "我要帮用户写测试。",
            "让我想想这个问题。",
            "让我看看代码结构。",
            "让我分析一下bug。",
            "这是一个复杂的问题。",
            "这需要仔细思考。",
            "首先，我需要理解代码。",
            "首先让我读取文件。",
            "好的，用户想让我写测试。",
            "那么我需要先分析代码。",
            "分析一下这段代码的问题。",
            "思考一下最佳方案。",
        ],
    )
    def test_reasoning_start_patterns(self, text):
        parser = MiniMaxReasoningParser()
        # Single line without transition → returned as content (no transition found)
        # The parser only classifies as reasoning if it can find a transition
        # or if there's a double newline split
        assert parser._REASONING_START_RE.match(text) is not None

    @pytest.mark.parametrize(
        "text",
        [
            "Hello, how are you?",
            "The weather is nice today.",
            "Welcome to the system.",
            "Python is a great language.",
        ],
    )
    def test_non_reasoning_start(self, text):
        parser = MiniMaxReasoningParser()
        reasoning, content = parser.extract_reasoning(text)

        assert reasoning is None
        assert content == text


class TestTransitionDetection:
    """Test transition from reasoning to content detection."""

    def test_transition_answer_is(self):
        parser = MiniMaxReasoningParser()
        output = "The user wants a poem.\n\nThe answer is: roses are red."

        reasoning, content = parser.extract_reasoning(output)

        assert reasoning == "The user wants a poem."
        assert content == "The answer is: roses are red."

    def test_transition_code_block(self):
        parser = MiniMaxReasoningParser()
        output = "Let me think about this.\n\n```python\nprint('hi')\n```"

        reasoning, content = parser.extract_reasoning(output)

        assert reasoning == "Let me think about this."
        assert content == "```python\nprint('hi')\n```"

    def test_transition_here_is(self):
        parser = MiniMaxReasoningParser()
        output = "I need to figure this out.\n\nHere is the solution."

        reasoning, content = parser.extract_reasoning(output)

        assert reasoning == "I need to figure this out."
        assert content == "Here is the solution."

    def test_transition_sure(self):
        parser = MiniMaxReasoningParser()
        output = "Let me analyze this.\n\nSure, here's the answer."

        reasoning, content = parser.extract_reasoning(output)

        assert reasoning == "Let me analyze this."
        assert content == "Sure, here's the answer."

    def test_transition_tool_call(self):
        parser = MiniMaxReasoningParser()
        output = "Let me think.\n<minimax:tool_call>call</minimax:tool_call>"

        reasoning, content = parser.extract_reasoning(output)

        assert reasoning == "Let me think."
        assert content is not None
        assert "<minimax:tool_call>" in content

    def test_transition_markdown_heading(self):
        parser = MiniMaxReasoningParser()
        output = "I need to analyze the code.\n\n## Analysis\n\nThe code has bugs."

        reasoning, content = parser.extract_reasoning(output)

        assert reasoning == "I need to analyze the code."
        assert "## Analysis" in content

    def test_transition_bold_text(self):
        parser = MiniMaxReasoningParser()
        output = "Let me review this.\n\n**Issue 1**: The code is wrong."

        reasoning, content = parser.extract_reasoning(output)

        assert reasoning == "Let me review this."
        assert "**Issue 1**" in content

    def test_transition_numbered_bold_list(self):
        parser = MiniMaxReasoningParser()
        output = "Analyzing the problem.\n\n1. **First** issue is here."

        reasoning, content = parser.extract_reasoning(output)

        assert reasoning is not None
        assert content is not None

    def test_short_reasoning_not_stripped(self):
        """Reasoning < 10 chars should NOT be separated (likely false positive)."""
        parser = MiniMaxReasoningParser()
        output = "I think\n\nHere is the answer."

        reasoning, content = parser.extract_reasoning(output)
        # "I think" is < 10 chars, so should be returned as content
        assert reasoning is None
        assert content == output

    def test_no_transition_double_newline_fallback(self):
        """When no transition regex matches, try double-newline split."""
        parser = MiniMaxReasoningParser()
        output = (
            "The user asks about Python.\n\nPython is a great language for beginners."
        )

        reasoning, content = parser.extract_reasoning(output)

        # Should split on double newline since first part matches reasoning
        assert reasoning == "The user asks about Python."
        assert content == "Python is a great language for beginners."

    def test_no_transition_no_split(self):
        """Single block of reasoning-like text → returned as content."""
        parser = MiniMaxReasoningParser()
        output = "The user asks about Python and it is great."

        reasoning, content = parser.extract_reasoning(output)

        # No transition, no double-newline split → content
        assert reasoning is None
        assert content == output


class TestStreamingBasic:
    """Test streaming parser with token-by-token input."""

    def test_direct_content_early_detection(self):
        """Content starting with code block should be detected immediately."""
        parser = MiniMaxReasoningParser()

        result = parser.extract_reasoning_streaming("", "```", "```")
        assert result is not None
        assert result.content == "```"
        assert parser._decided is True
        assert parser._is_reasoning is False

    def test_direct_content_tool_call(self):
        parser = MiniMaxReasoningParser()

        result = parser.extract_reasoning_streaming(
            "", "<minimax:tool_call>", "<minimax:tool_call>"
        )
        assert result is not None
        assert result.content == "<minimax:tool_call>"

    def test_buffer_phase_returns_none(self):
        """During buffer phase (< 80 chars), parser should return None."""
        parser = MiniMaxReasoningParser()

        # Short text that doesn't match direct content
        result = parser.extract_reasoning_streaming("", "The user", "The user")
        assert result is None
        assert parser._decided is False

    def test_buffer_accumulates(self):
        """Buffer should accumulate across calls."""
        parser = MiniMaxReasoningParser()

        r1 = parser.extract_reasoning_streaming("", "The ", "The ")
        assert r1 is None

        r2 = parser.extract_reasoning_streaming("The ", "The user ", "user ")
        assert r2 is None

        assert parser._buffer == "The user "

    def test_reasoning_detected_after_buffer(self):
        """After buffer fills, reasoning pattern should be detected."""
        parser = MiniMaxReasoningParser()

        # Build up buffer to > 80 chars with reasoning pattern
        text = "The user asks about a very complex topic that requires deep analysis and careful thinking to solve properly."
        # Feed character by character until decision
        current = ""
        last_result = None
        for ch in text:
            prev = current
            current += ch
            result = parser.extract_reasoning_streaming(prev, current, ch)
            if result is not None:
                last_result = result

        assert parser._decided is True
        assert parser._is_reasoning is True
        # The flush should contain the full accumulated text as reasoning
        assert last_result is not None
        assert last_result.reasoning is not None

    def test_content_detected_after_buffer(self):
        """Non-reasoning text should be flushed as content after buffer fills."""
        parser = MiniMaxReasoningParser()

        # Build up buffer > 80 chars with non-reasoning text
        text = "Hello! Welcome to our service. We are happy to help you with your question about programming today."
        current = ""
        last_result = None
        for ch in text:
            prev = current
            current += ch
            result = parser.extract_reasoning_streaming(prev, current, ch)
            if result is not None:
                last_result = result

        assert parser._decided is True
        assert parser._is_reasoning is False
        assert last_result is not None
        assert last_result.content is not None


class TestStreamingThinkTags:
    """Test streaming with explicit <think> tags."""

    def test_think_tag_start(self):
        parser = MiniMaxReasoningParser()

        result = parser.extract_reasoning_streaming("", "<think>", "<think>")
        assert result is None  # Tag itself is skipped
        assert parser._decided is True
        assert parser._is_reasoning is True

    def test_think_tag_with_content(self):
        parser = MiniMaxReasoningParser()

        result = parser.extract_reasoning_streaming(
            "", "<think>reasoning", "<think>reasoning"
        )
        assert result is not None
        assert result.reasoning == "reasoning"

    def test_think_tag_end(self):
        parser = MiniMaxReasoningParser()

        # Start with think tag
        parser.extract_reasoning_streaming("", "<think>", "<think>")

        # Add reasoning
        parser.extract_reasoning_streaming(
            "<think>", "<think>some reasoning", "some reasoning"
        )

        # End think tag
        result = parser.extract_reasoning_streaming(
            "<think>some reasoning",
            "<think>some reasoning</think>content here",
            "</think>content here",
        )
        assert result is not None
        assert result.content == "content here"
        assert parser._is_reasoning is False

    def test_think_tag_end_no_content(self):
        parser = MiniMaxReasoningParser()

        parser.extract_reasoning_streaming("", "<think>", "<think>")
        result = parser.extract_reasoning_streaming(
            "<think>", "<think></think>", "</think>"
        )

        assert result is not None
        # Both reasoning and content should be None/empty
        assert parser._is_reasoning is False


class TestStreamingTransition:
    """Test streaming transition from reasoning to content."""

    def test_transition_during_stream(self):
        """Reasoning followed by content transition in streaming."""
        parser = MiniMaxReasoningParser()

        # Feed reasoning text past buffer threshold
        reasoning_text = "The user asks about a complex topic that requires very careful analysis and deep thinking to answer properly."
        current = ""
        for ch in reasoning_text:
            prev = current
            current += ch
            parser.extract_reasoning_streaming(prev, current, ch)

        assert parser._decided is True
        assert parser._is_reasoning is True

        # Now feed a transition marker
        prev = current
        transition = "\n\nHere is the answer."
        current += transition
        result = parser.extract_reasoning_streaming(prev, current, transition)

        # Should detect transition and switch to content
        assert result is not None
        if result.content:
            assert "Here is" in result.content

    def test_post_decision_content_passthrough(self):
        """After deciding content, subsequent tokens pass through."""
        parser = MiniMaxReasoningParser()

        # Trigger content decision with code block
        parser.extract_reasoning_streaming("", "```python", "```python")

        # Subsequent tokens should pass through as content
        result = parser.extract_reasoning_streaming(
            "```python", "```python\nprint", "\nprint"
        )
        assert result is not None
        assert result.content == "\nprint"


class TestFinalizeStreaming:
    """Test finalize_streaming behavior."""

    def test_finalize_undecided_with_text(self):
        """If never decided, finalize should emit buffer as content."""
        parser = MiniMaxReasoningParser()

        # Feed a little text (stays in buffer phase)
        parser.extract_reasoning_streaming("", "Short", "Short")
        assert parser._decided is False

        result = parser.finalize_streaming("Short")
        assert result is not None
        assert result.content == "Short"

    def test_finalize_undecided_empty(self):
        """If never decided and no text, finalize returns None."""
        parser = MiniMaxReasoningParser()

        result = parser.finalize_streaming("")
        assert result is None

    def test_finalize_decided_content(self):
        """If decided as content, finalize returns None (nothing extra)."""
        parser = MiniMaxReasoningParser()
        parser._decided = True
        parser._is_reasoning = False

        result = parser.finalize_streaming("some content")
        assert result is None

    def test_finalize_all_reasoning_reclassify(self):
        """If everything was reasoning with no content, reclassify as content."""
        parser = MiniMaxReasoningParser()
        parser._decided = True
        parser._is_reasoning = True

        result = parser.finalize_streaming("The user asks about Python.")
        assert result is not None
        assert result.content is not None


class TestEdgeCases:
    """Test edge cases and boundary conditions."""

    def test_empty_input_extract(self):
        parser = MiniMaxReasoningParser()
        reasoning, content = parser.extract_reasoning("")

        assert reasoning is None
        assert content == ""

    def test_whitespace_only_extract(self):
        parser = MiniMaxReasoningParser()
        reasoning, content = parser.extract_reasoning("   \n\n   ")

        assert reasoning is None
        assert content == "   \n\n   "

    def test_very_long_reasoning_no_transition(self):
        """Very long text matching reasoning start but no transition."""
        parser = MiniMaxReasoningParser()
        output = "The user asks " + "word " * 200

        reasoning, content = parser.extract_reasoning(output)
        # Should return as content (conservative — can't separate)
        assert content is not None

    def test_streaming_single_char_at_a_time(self):
        """Stream character by character to test robustness."""
        parser = MiniMaxReasoningParser()
        text = "```python\nprint('hello')\n```"

        current = ""
        results = []
        for ch in text:
            prev = current
            current += ch
            result = parser.extract_reasoning_streaming(prev, current, ch)
            if result is not None:
                results.append(result)

        # Should have at least one result (content flush on ```)
        assert len(results) >= 1
        # All results should be content (code block)
        for r in results:
            assert r.reasoning is None

    def test_reset_between_streams(self):
        """Reset should allow reuse for a new stream."""
        parser = MiniMaxReasoningParser()

        # First stream
        parser.extract_reasoning_streaming(
            "", "<think>stuff</think>content", "<think>stuff</think>content"
        )
        assert parser._decided is True

        # Reset
        parser.reset_state()
        assert parser._decided is False
        assert parser._buffer == ""

        # Second stream should work fresh
        result = parser.extract_reasoning_streaming("", "```code", "```code")
        assert result is not None
        assert result.content == "```code"

    def test_thus_answer_transition(self):
        """MiniMax-specific: 'Thus answer:' pattern."""
        parser = MiniMaxReasoningParser()
        output = "I need to analyze this carefully.\nThus answer: The result is 42."

        reasoning, content = parser.extract_reasoning(output)
        assert reasoning == "I need to analyze this carefully."
        assert content == "Thus answer: The result is 42."

    def test_chinese_reasoning_then_content(self):
        """Chinese reasoning followed by content transition."""
        parser = MiniMaxReasoningParser()
        output = "用户想让我写一个快速排序算法。\n\n```python\ndef quicksort(arr):\n    pass\n```"

        reasoning, content = parser.extract_reasoning(output)
        assert reasoning == "用户想让我写一个快速排序算法。"
        assert "```python" in content

    def test_chinese_reasoning_streaming(self):
        """Chinese reasoning detected in streaming mode."""
        parser = MiniMaxReasoningParser()

        text = "用户想让我分析这段代码并找出所有的bug。这个代码有很多潜在的安全问题和性能瓶颈需要仔细检查，包括SQL注入攻击、线程安全竞态条件和内存泄漏等方面的问题，还需要考虑错误处理和边界情况。"
        current = ""
        last_result = None
        for ch in text:
            prev = current
            current += ch
            result = parser.extract_reasoning_streaming(prev, current, ch)
            if result is not None:
                last_result = result

        assert parser._decided is True
        assert parser._is_reasoning is True
        assert last_result is not None
        assert last_result.reasoning is not None

    def test_chinese_transition_pattern(self):
        """Chinese transition: '以下是' after reasoning."""
        parser = MiniMaxReasoningParser()
        output = "我需要分析这段代码。\n\n以下是修复后的代码。"

        reasoning, content = parser.extract_reasoning(output)
        assert reasoning == "我需要分析这段代码。"
        assert "以下是" in content
