#!/usr/bin/env python3
"""Agent Integration Test Generator — creates test_<agent>.py from a config.

Takes a YAML/JSON config describing an agent's setup and generates a complete
integration test file based on the test_hermes.py template.

Usage:
    # Interactive — prompts for agent details
    python3 scripts/agent_test_gen.py

    # From config file
    python3 scripts/agent_test_gen.py --config agents/myagent.yaml

    # Quick — minimal config via CLI args
    python3 scripts/agent_test_gen.py --name "myagent" \
        --binary "~/.local/bin/myagent" \
        --config-type env \
        --config-keys "OPENAI_BASE_URL,OPENAI_API_KEY,OPENAI_MODEL" \
        --query-cmd "myagent chat -q '{query}'"

Config YAML format:
    name: myagent
    display_name: "My Agent"
    repo: "owner/myagent"
    stars: 5000
    binary: "~/.local/bin/myagent"
    config_type: env | yaml | json
    config_path: "~/.myagent/config.yaml"  # for yaml/json type
    config_template: |
      model:
        base_url: "{base_url}"
        model: "{model_id}"
    env_vars:                                # for env type
      OPENAI_BASE_URL: "{base_url}"
      OPENAI_API_KEY: "not-needed"
      OPENAI_MODEL: "{model_id}"
    query_cmd: "myagent chat -q '{query}'"
    query_timeout: 120
    tools_injected: 10                       # how many tools agent injects
    known_issues: []
"""

import argparse
import sys
from datetime import datetime


def generate_test_file(config):
    """Generate a complete integration test file from config."""
    name = config["name"]
    display = config.get("display_name", name.title())
    repo = config.get("repo", f"unknown/{name}")
    binary = config.get("binary", f"~/.local/bin/{name}")
    config_type = config.get("config_type", "env")
    query_cmd = config.get("query_cmd", f"{name} chat -q '{{query}}'")
    query_timeout = config.get("query_timeout", 120)
    tools_injected = config.get("tools_injected", 0)

    # Pre-compute conditional blocks (avoid backslash-in-fstring on Python 3.10)
    many_tools_def = "def test_api_many_tools():" if tools_injected > 0 else "# Skipped: agent does not inject many tools"
    many_tools_body = _gen_many_tools_test(tools_injected) if tools_injected > 0 else ""
    many_tools_run = '    run_test("api_many_tools", test_api_many_tools)' if tools_injected > 0 else "    # Skipped: api_many_tools (agent doesn't inject tools)"

    # Build the config setup function
    if config_type == "yaml":
        config_path = config.get("config_path", f"~/.{name}/config.yaml")
        template = config.get("config_template", "")
        config_setup = _gen_yaml_config(name, config_path, template)
    elif config_type == "json":
        config_path = config.get("config_path", f"~/.{name}/config.json")
        template = config.get("config_template", "{}")
        config_setup = _gen_json_config(name, config_path, template)
    else:  # env
        env_vars = config.get("env_vars", {
            "OPENAI_BASE_URL": "{base_url}",
            "OPENAI_API_KEY": "not-needed",
        })
        config_setup = _gen_env_config(name, env_vars)

    # Parse query command into subprocess args
    query_parts = query_cmd.replace("'{query}'", "QUERY_PLACEHOLDER").split()
    query_args = query_parts[1:]

    return f'''"""{ display } integration tests against local Rapid-MLX server.

Tests the full { display } → Rapid-MLX pipeline using the OpenAI-compatible
API. Covers chat, tool calling (single, multi-step, parallel), streaming,
and edge cases.

Requirements:
    1. Rapid-MLX server running: rapid-mlx serve <MODEL> --port 8000
    2. { display } installed (see { repo })
    3. Agent configured to point to localhost:8000

Generated by: scripts/agent_test_gen.py on {datetime.now().strftime("%Y-%m-%d")}
Template: tests/integrations/test_hermes.py
"""

import json
import os
import subprocess
import sys
import time
import httpx

BASE_URL = os.environ.get("RAPID_MLX_BASE_URL", "http://localhost:8000/v1")
# Auto-detect model from server
try:
    resp = httpx.get(f"{{BASE_URL}}/models", timeout=5)
    MODEL_ID = resp.json()["data"][0]["id"]
except Exception:
    MODEL_ID = "default"

{name.upper()}_BIN = os.environ.get(
    "{name.upper()}_BIN",
    os.path.expanduser("{binary}"),
)

results = {{}}


def api_call(messages, tools=None, stream=False, max_tokens=300, temperature=0.3):
    """Direct API call to Rapid-MLX server."""
    payload = {{
        "model": MODEL_ID,
        "messages": messages,
        "max_tokens": max_tokens,
        "temperature": temperature,
        "stream": stream,
    }}
    if tools:
        payload["tools"] = tools
    resp = httpx.post(
        f"{{BASE_URL}}/chat/completions",
        json=payload,
        timeout=120,
    )
    resp.raise_for_status()
    return resp.json()


{config_setup}


def {name}_query(query, timeout_sec={query_timeout}):
    """Run a single { display } query in non-interactive mode."""
    if not os.path.exists({name.upper()}_BIN):
        return None, "SKIP: {name} binary not found"
    try:
        proc = subprocess.run(
            [{name.upper()}_BIN, {", ".join(repr(a).replace("QUERY_PLACEHOLDER", '" + query + "') for a in query_args)}],
            capture_output=True,
            text=True,
            timeout=timeout_sec,
            cwd=os.getcwd(),
        )
        output = proc.stdout + proc.stderr
        if "error" in output.lower() and "HTTP 4" in output:
            return None, f"{ display } error: server issue"
        return output, None
    except subprocess.TimeoutExpired:
        return None, "TIMEOUT"
    except Exception as e:
        return None, str(e)


def run_test(name, fn):
    """Run a test function and record the result."""
    print(f"\\n{{"="*60}}")
    print(f"Test: {{name}}")
    print(f"{{"="*60}}")
    try:
        fn()
        results[name] = "PASS"
        print(f"  ✅ PASS")
    except AssertionError as e:
        results[name] = f"FAIL: {{e}}"
        print(f"  ❌ FAIL: {{e}}")
    except Exception as e:
        results[name] = f"ERROR: {{e}}"
        print(f"  ❌ ERROR: {{e}}")


# =============================================================================
# API-level tests (no { display } binary needed)
# =============================================================================

BASIC_TOOLS = [
    {{
        "type": "function",
        "function": {{
            "name": "read_file",
            "description": "Read file contents",
            "parameters": {{
                "type": "object",
                "properties": {{"path": {{"type": "string"}}}},
                "required": ["path"],
            }},
        }},
    }},
    {{
        "type": "function",
        "function": {{
            "name": "terminal",
            "description": "Execute a shell command",
            "parameters": {{
                "type": "object",
                "properties": {{"command": {{"type": "string"}}}},
                "required": ["command"],
            }},
        }},
    }},
    {{
        "type": "function",
        "function": {{
            "name": "search_files",
            "description": "Search for files by pattern",
            "parameters": {{
                "type": "object",
                "properties": {{
                    "pattern": {{"type": "string"}},
                    "path": {{"type": "string"}},
                }},
                "required": ["pattern"],
            }},
        }},
    }},
]


def test_api_plain_chat():
    """Basic chat without tools."""
    r = api_call([{{"role": "user", "content": "What is 2+2? Reply with just the number."}}])
    content = r["choices"][0]["message"]["content"]
    assert "4" in content, f"Expected '4' in: {{content[:100]}}"
    print(f"  Response: {{content[:80]}}")


def test_api_single_tool_call():
    """Single tool call with structured response."""
    r = api_call(
        [{{"role": "user", "content": "Read the file /etc/hostname"}}],
        tools=BASIC_TOOLS,
    )
    msg = r["choices"][0]["message"]
    assert msg.get("tool_calls"), f"No tool_calls in response: {{msg}}"
    tc = msg["tool_calls"][0]
    assert tc["function"]["name"] == "read_file", f"Wrong tool: {{tc['function']['name']}}"
    print(f"  Tool: {{tc['function']['name']}}")


def test_api_tool_choice():
    """Model correctly picks the right tool from multiple options."""
    r = api_call(
        [{{"role": "user", "content": "Run the command 'echo hello'"}}],
        tools=BASIC_TOOLS,
    )
    msg = r["choices"][0]["message"]
    assert msg.get("tool_calls"), f"No tool_calls: {{msg.get('content', '')[:100]}}"
    tc = msg["tool_calls"][0]
    assert tc["function"]["name"] == "terminal", f"Wrong tool: {{tc['function']['name']}}"
    print(f"  Correctly chose: terminal")


def test_api_multi_turn_tool():
    """Multi-turn: tool call → tool result → follow-up."""
    r1 = api_call(
        [{{"role": "user", "content": "Read /etc/hosts"}}],
        tools=BASIC_TOOLS,
    )
    msg1 = r1["choices"][0]["message"]
    assert msg1.get("tool_calls"), "First turn should trigger tool call"

    r2 = api_call(
        [
            {{"role": "user", "content": "Read /etc/hosts"}},
            {{
                "role": "assistant",
                "content": None,
                "tool_calls": msg1["tool_calls"],
            }},
            {{
                "role": "tool",
                "tool_call_id": msg1["tool_calls"][0]["id"],
                "content": "127.0.0.1 localhost\\n::1 localhost",
            }},
            {{"role": "user", "content": "What IP addresses are in that file?"}},
        ],
        tools=BASIC_TOOLS,
    )
    content2 = r2["choices"][0]["message"]["content"]
    assert "127.0.0.1" in content2 or "localhost" in content2, f"Bad follow-up: {{content2[:100]}}"
    print(f"  Multi-turn OK")


def test_api_no_tool_leak():
    """Ensure no raw <tool_call> tags leak into content."""
    r = api_call(
        [{{"role": "user", "content": "Use the terminal to run 'echo test'"}}],
        tools=BASIC_TOOLS,
    )
    msg = r["choices"][0]["message"]
    content = msg.get("content", "")
    assert "<tool_call>" not in content, f"Tag leak: {{content[:200]}}"
    assert "<function=" not in content, f"Function tag leak: {{content[:200]}}"
    assert "<|im_end|>" not in content, f"EOS leak: {{content[:200]}}"
    print(f"  No tag leaks detected")


{many_tools_def}
{many_tools_body}


def test_api_streaming_tool_call():
    """Streaming mode: tool calls arrive as structured deltas."""
    payload = {{
        "model": MODEL_ID,
        "messages": [{{"role": "user", "content": "Read the file /etc/hosts"}}],
        "tools": BASIC_TOOLS,
        "max_tokens": 200,
        "stream": True,
    }}
    with httpx.stream(
        "POST", f"{{BASE_URL}}/chat/completions", json=payload, timeout=60
    ) as resp:
        tool_call_chunks = []
        finish_reason = None
        for line in resp.iter_lines():
            if not line.startswith("data: ") or line == "data: [DONE]":
                continue
            data = json.loads(line[6:])
            delta = data["choices"][0].get("delta", {{}})
            if "tool_calls" in delta:
                tool_call_chunks.append(delta["tool_calls"])
            if data["choices"][0].get("finish_reason"):
                finish_reason = data["choices"][0]["finish_reason"]

    assert tool_call_chunks, "No tool_call chunks in stream"
    assert finish_reason == "tool_calls", f"finish_reason={{finish_reason}}"
    print(f"  Streaming: {{len(tool_call_chunks)}} tool chunks")


def test_api_no_tool_needed():
    """When tools are provided but not needed, model should answer directly."""
    r = api_call(
        [{{"role": "user", "content": "What is the capital of France?"}}],
        tools=BASIC_TOOLS,
    )
    msg = r["choices"][0]["message"]
    content = msg.get("content", "")
    assert "paris" in content.lower(), f"Expected Paris: {{content[:100]}}"
    print(f"  Answered without tools: {{content[:60]}}")


def test_api_parallel_tool_calls():
    """Model can request multiple tool calls in one response."""
    r = api_call(
        [{{"role": "user", "content": "Read both /etc/hosts and /etc/resolv.conf at the same time"}}],
        tools=BASIC_TOOLS,
        max_tokens=500,
    )
    msg = r["choices"][0]["message"]
    content = msg.get("content", "")
    assert "<tool_call>" not in content, f"Tag leak: {{content[:100]}}"
    if msg.get("tool_calls") and len(msg["tool_calls"]) >= 2:
        print(f"  Parallel calls: {{[tc['function']['name'] for tc in msg['tool_calls']]}}")
    else:
        print(f"  Sequential (model choice)")


def test_api_stress_no_leak():
    """10 rapid tool calls — zero tag leaks."""
    leaked = 0
    for i in range(10):
        r = api_call(
            [{{"role": "user", "content": f"Run: echo test_{{i}}"}}],
            tools=BASIC_TOOLS,
            temperature=0.8,
        )
        content = r["choices"][0]["message"].get("content", "")
        if "<tool_call>" in content or "<function=" in content:
            leaked += 1
    assert leaked == 0, f"{{leaked}}/10 requests had tag leaks"
    print(f"  0/10 tag leaks at temperature=0.8")


# =============================================================================
# { display } E2E tests (requires { name } binary)
# =============================================================================

def test_{name}_chat():
    """Basic { display } chat (no tool use)."""
    out, err = {name}_query("What is 2+2? Reply with just the number.")
    if err:
        assert False, err
    assert "4" in out, f"Expected 4 in: {{out[:100]}}"
    print(f"  Output: {{out.strip()[:80]}}")


def test_{name}_read_file():
    """{ display } reads a file via tool call."""
    out, err = {name}_query("Read the first line of pyproject.toml")
    if err:
        assert False, err
    assert "build" in out.lower() or "project" in out.lower(), f"Unexpected: {{out[:100]}}"
    print(f"  Read file: OK")


def test_{name}_terminal():
    """{ display } runs a shell command."""
    out, err = {name}_query("Run 'echo rapid_mlx_{name}_test' and show me the output")
    if err:
        assert False, err
    assert "rapid_mlx_{name}_test" in out, f"Command output missing: {{out[:100]}}"
    print(f"  Terminal: OK")


def test_{name}_multi_step():
    """{ display } does a multi-step task (search → read → analyze)."""
    out, err = {name}_query(
        "Find the file aliases.json, read it, and tell me how many entries it has",
        timeout_sec=180,
    )
    if err:
        assert False, err
    assert any(str(n) in out for n in range(10, 50)), f"No count found: {{out[:200]}}"
    print(f"  Multi-step: OK")


def test_{name}_write_and_run():
    """{ display } writes a Python script and executes it."""
    out, err = {name}_query(
        "Create a Python script at /tmp/{name}_test_fib.py that prints the first "
        "10 fibonacci numbers as a comma-separated list, then run it and show output",
        timeout_sec=120,
    )
    if err:
        assert False, err
    result = subprocess.run(
        ["python3", "/tmp/{name}_test_fib.py"],
        capture_output=True, text=True, timeout=10,
    )
    fib_out = result.stdout + out
    assert any(str(n) in fib_out for n in [8, 13, 21, 34]), f"Fibonacci missing: {{fib_out[:200]}}"
    print(f"  Write+run: OK")


# =============================================================================
# Main
# =============================================================================

if __name__ == "__main__":
    print(f"Rapid-MLX { display } Integration Tests")
    print(f"Server: {{BASE_URL}}")
    print(f"Model:  {{MODEL_ID}}")
    print(f"Agent:  {{{name.upper()}_BIN}}")
    print(f"{{"="*60}}")

    t0 = time.time()

    # API-level tests (always run)
    run_test("api_plain_chat", test_api_plain_chat)
    run_test("api_single_tool_call", test_api_single_tool_call)
    run_test("api_tool_choice", test_api_tool_choice)
    run_test("api_multi_turn_tool", test_api_multi_turn_tool)
    run_test("api_no_tool_leak", test_api_no_tool_leak)
{many_tools_run}
    run_test("api_streaming_tool_call", test_api_streaming_tool_call)
    run_test("api_no_tool_needed", test_api_no_tool_needed)
    run_test("api_parallel_tool_calls", test_api_parallel_tool_calls)
    run_test("api_stress_no_leak", test_api_stress_no_leak)

    # { display } E2E tests (require binary)
    if os.path.exists({name.upper()}_BIN):
        ensure_{name}_config()
        run_test("{name}_chat", test_{name}_chat)
        run_test("{name}_read_file", test_{name}_read_file)
        run_test("{name}_terminal", test_{name}_terminal)
        run_test("{name}_multi_step", test_{name}_multi_step)
        run_test("{name}_write_and_run", test_{name}_write_and_run)
    else:
        print(f"\\n⚠️ Skipping { display } E2E tests: {{{name.upper()}_BIN}} not found")

    elapsed = time.time() - t0
    passed = sum(1 for v in results.values() if v == "PASS")
    failed = sum(1 for v in results.values() if v != "PASS")

    print(f"\\n{{"="*60}}")
    print(f"Results: {{passed}}/{{len(results)}} passed ({{elapsed:.1f}}s)")
    print(f"Model:   {{MODEL_ID}}")
    print(f"{{"="*60}}")
    for name_key, status in results.items():
        icon = "✅" if status == "PASS" else "❌"
        print(f"  {{icon}} {{name_key}}: {{status}}")

    if failed:
        sys.exit(1)
'''


def _gen_yaml_config(name, config_path, template):
    """Generate YAML config setup function."""
    return f'''def ensure_{name}_config():
    """Update {name} config to point to the current server/model."""
    config_dir = os.path.dirname(os.path.expanduser("{config_path}"))
    os.makedirs(config_dir, exist_ok=True)
    config_path = os.path.expanduser("{config_path}")
    base_url = BASE_URL
    config = f"""{template}"""
    with open(config_path, "w") as f:
        f.write(config)
'''


def _gen_json_config(name, config_path, template):
    """Generate JSON config setup function."""
    return f'''def ensure_{name}_config():
    """Update {name} config to point to the current server/model."""
    config_dir = os.path.dirname(os.path.expanduser("{config_path}"))
    os.makedirs(config_dir, exist_ok=True)
    config_path = os.path.expanduser("{config_path}")
    config = {{
        "base_url": BASE_URL,
        "model": MODEL_ID,
        "api_key": "not-needed",
    }}
    with open(config_path, "w") as f:
        json.dump(config, f, indent=2)
'''


def _gen_env_config(name, env_vars):
    """Generate env var config setup function."""
    lines = []
    for key, val in env_vars.items():
        val_expr = val.replace("{base_url}", "' + BASE_URL + '").replace("{model_id}", "' + MODEL_ID + '")
        lines.append(f'    os.environ["{key}"] = \'{val_expr}\'')
    env_lines = "\n".join(lines)
    return f'''def ensure_{name}_config():
    """Set environment variables for {name}."""
{env_lines}
'''


def _gen_many_tools_test(tools_count):
    """Generate many-tools test."""
    return f'''    """Test with {tools_count}+ tools (simulating agent's tool setup)."""
    many_tools = []
    for i in range({tools_count}):
        many_tools.append({{
            "type": "function",
            "function": {{
                "name": f"tool_{{i}}",
                "description": f"Tool number {{i}}",
                "parameters": {{
                    "type": "object",
                    "properties": {{"arg": {{"type": "string"}}}},
                    "required": ["arg"],
                }},
            }},
        }})
    many_tools.extend(BASIC_TOOLS)

    r = api_call(
        [{{"role": "user", "content": "Run the command 'echo hello_many_tools'"}}],
        tools=many_tools,
    )
    msg = r["choices"][0]["message"]
    assert msg.get("tool_calls"), f"No tool call with {{len(many_tools)}} tools"
    tc = msg["tool_calls"][0]
    assert tc["function"]["name"] == "terminal", f"Wrong tool: {{tc['function']['name']}}"
    print(f"  Correct tool with {{len(many_tools)}} tools")

'''


def interactive_config():
    """Interactively build an agent config."""
    print("🔧 Agent Integration Test Generator")
    print("="*50)

    config = {}
    config["name"] = input("Agent name (lowercase, no spaces): ").strip()
    config["display_name"] = input(f"Display name [{config['name'].title()}]: ").strip() or config["name"].title()
    config["repo"] = input("GitHub repo (owner/name): ").strip()
    config["binary"] = input("Binary path [~/.local/bin/<name>]: ").strip() or f"~/.local/bin/{config['name']}"

    print("\nConfig type:")
    print("  1. env  — environment variables (OPENAI_BASE_URL etc)")
    print("  2. yaml — YAML config file")
    print("  3. json — JSON config file")
    ct = input("Choice [1]: ").strip() or "1"
    config["config_type"] = {"1": "env", "2": "yaml", "3": "json"}[ct]

    if config["config_type"] in ("yaml", "json"):
        config["config_path"] = input(f"Config path [~/.{config['name']}/config.{config['config_type']}]: ").strip() \
            or f"~/.{config['name']}/config.{config['config_type']}"

    config["query_cmd"] = input(f"Query command [{config['name']} chat -q '{{query}}']: ").strip() \
        or f"{config['name']} chat -q '{{query}}'"
    config["query_timeout"] = int(input("Query timeout sec [120]: ").strip() or "120")

    ti = input("How many tools does the agent inject per request? [0]: ").strip() or "0"
    config["tools_injected"] = int(ti)

    return config


def main():
    parser = argparse.ArgumentParser(description="Generate agent integration tests")
    parser.add_argument("--config", help="YAML config file for the agent")
    parser.add_argument("--name", help="Agent name (for CLI mode)")
    parser.add_argument("--binary", help="Agent binary path")
    parser.add_argument("--config-type", choices=["env", "yaml", "json"], default="env")
    parser.add_argument("--config-keys", help="Comma-separated env var names")
    parser.add_argument("--query-cmd", help="Query command template")
    parser.add_argument("--output", "-o", help="Output file (default: tests/integrations/test_<name>.py)")
    args = parser.parse_args()

    if args.config:
        try:
            import yaml
        except ImportError:
            sys.exit("Error: pyyaml required for --config. Install: pip install pyyaml")
        with open(args.config) as f:
            config = yaml.safe_load(f)
    elif args.name:
        config = {
            "name": args.name,
            "binary": args.binary or f"~/.local/bin/{args.name}",
            "config_type": args.config_type,
            "query_cmd": args.query_cmd or f"{args.name} chat -q '{{query}}'",
        }
    else:
        config = interactive_config()

    output_path = args.output or f"tests/integrations/test_{config['name']}.py"
    test_code = generate_test_file(config)

    with open(output_path, "w") as f:
        f.write(test_code)

    print(f"\n✅ Generated: {output_path}")
    print(f"   {len(test_code.splitlines())} lines, ~15 tests")
    print("\nNext steps:")
    print(f"  1. Review and customize: {output_path}")
    print("  2. Start server: rapid-mlx serve <MODEL>")
    print(f"  3. Run tests:    python3 {output_path}")


if __name__ == "__main__":
    main()
